add component calendar
js-tasks-ru/htmlcss-20210812_bleshunov5b pull request #12
Opened 2021-08-28 15:13 UTC by bleschunov

2021-08-28 15:14 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-08-29 09:47 UTC, GSemikozov requested changes

2021-08-29 09:47 UTC, GSemikozov commented on 05-lection3/03-calendar/calendar.css
> +.calendar__number_selected {
.calendar__number_selected и .calendar__number_selected-between это модификаторы, не нужно дублировать весь код для ячейки, достаточно указать то специфическое что модифицируем (фон, цвет)

2021-08-29 15:20 UTC, bleschunov commented on 05-lection3/03-calendar/calendar.css
> +.calendar__number_selected {
исправил

2021-08-30 08:27 UTC, GSemikozov approved these changes

2021-08-30 08:27 UTC, merged