add solution for modal task
js-tasks-ru/htmlcss-20210812_bleshunov5b pull request #13
Opened 2021-08-29 07:54 UTC by bleschunov

2021-08-29 07:54 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-08-29 09:49 UTC, GSemikozov requested changes

2021-08-29 09:49 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +.button_primary {
не понял зачем здесь поменяли класс - все было правильно, общие стили для всех типов кнопок описываются в общем классе

2021-08-29 09:49 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +  width: 182px;
а теперь получается что для каждого типа кнопки мы дублируем одни и те же стили

2021-08-29 09:49 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +  position: absolute;
критически важно позиционировать через fixed

2021-08-29 09:49 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +  background-color: var(--grey-6);
фон должен быть полупрозрачным

2021-08-29 15:11 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-08-29 15:16 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-08-29 15:18 UTC, bleschunov commented on 03-lection1/01-button/button.css
> +.button_primary {
вернул. 
мне больше нравится, когда мы в классах пишем button_primary вместо button button_primary. мне так кажется более последовательно. а то не понятно, в каких компонентах модификатор обязательный, а в каких нет.

2021-08-29 15:18 UTC, bleschunov commented on 03-lection1/01-button/button.css
> +  width: 182px;
+

2021-08-29 15:19 UTC, bleschunov commented on 05-lection3/02-modal/modal.css
> +  position: absolute;
исправил.
почему это важно, если все равно мы запрещаем прокрутку страницы?

2021-08-29 15:20 UTC, bleschunov commented on 05-lection3/02-modal/modal.css
> +  background-color: var(--grey-6);
grey-6 указал в main.css через rgba

2021-08-30 08:29 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +.button_primary {
наоборот - БЭМ позволяет избегать дублирования одного и того же кода. Мы используем компонент с модификаторами, так надежнее и понятнее, и при создании нового типа кнопок нам не надо заново описывать одни и те же стили. А если придется поменять например по дизайну паддинги - то придется менять во всех таких определениях (если для каждого типа описывать одни и те же стили отдельно)

2021-08-30 08:31 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +  position: absolute;
при absolute при привязываемся к непосредственному родителю, и если наш родитель будет ниже ко коду в странице, а кнопка вызова наоборот где-нибудь наверху - то нашу модалку мы никогда не увидим)

2021-08-31 06:15 UTC, bleschunov commented on 05-lection3/02-modal/modal.css
> +  position: absolute;
тогда и у класса .modal__window также нужно сделать position: fixed. верно?

2021-08-31 08:08 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +  position: absolute;
нет, window будет позиционироваться относительно родителя с fixed, поэтому достаточно absolute

2021-08-31 09:49 UTC, bleschunov commented on 05-lection3/02-modal/modal.css
> +  position: absolute;
понял

2021-08-31 10:32 UTC, GSemikozov approved these changes

2021-08-31 10:32 UTC, merged