add solution for radio
js-tasks-ru/htmlcss-20210812_bleshunov5b pull request #21
Opened 2021-09-04 17:42 UTC by bleschunov

2021-09-04 17:43 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-09-05 11:09 UTC, GSemikozov requested changes

2021-09-05 11:09 UTC, GSemikozov commented on 07-lection5/02-radio/radio.css
> +.radio_label {
.radio_label -> .radio__label

2021-09-05 11:09 UTC, GSemikozov commented on 07-lection5/02-radio/radio.css
> +  border: 2px solid var(--grey-2);
можно более точечно: border-color

2021-09-09 04:50 UTC, bleschunov commented on 07-lection5/02-radio/radio.css
> +.radio_label {
исправил

2021-09-09 04:50 UTC, bleschunov commented on 07-lection5/02-radio/radio.css
> +  border: 2px solid var(--grey-2);
исправил

2021-09-09 10:12 UTC, GSemikozov approved these changes

2021-09-09 10:12 UTC, merged