add solution for input task
js-tasks-ru/htmlcss-20210812_bleshunov5b pull request #23
Opened 2021-09-04 19:31 UTC by bleschunov

2021-09-04 19:32 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-09-05 11:17 UTC, GSemikozov requested changes

2021-09-05 11:17 UTC, GSemikozov commented on 07-lection5/04-input/input.css
> +.input__field {
обычно еще задают appearance: none чтобы сбросиить потенциальные отрисовки браузером

2021-09-05 11:17 UTC, GSemikozov commented on 07-lection5/04-input/input.css
> +  height: 100%;
высоту лучше задать по инпуту, а не по врапперу

2021-09-05 11:17 UTC, GSemikozov commented on 07-lection5/04-input/input.css
> +  fill: white;
1. цвета берем из переменных
2. вместо fill лучше color + currentColor в иконке
3. по умолчанию иконка скрыта и показывается только если .input_invalid или .input_success

2021-09-09 05:09 UTC, bleschunov commented on 07-lection5/04-input/input.css
> +.input__field {
пробовал, но вообще не понял, что это меняет, так что решил не применять.

2021-09-09 09:51 UTC, bleschunov commented on 07-lection5/04-input/input.css
> +  fill: white;
все исправил

2021-09-09 09:51 UTC, bleschunov commented on 07-lection5/04-input/input.css
> +  height: 100%;
сделал

2021-09-09 09:51 UTC, bleschunov commented on 07-lection5/04-input/input.css
> +  height: 100%;
почему так лучше?

2021-09-09 10:18 UTC, GSemikozov commented on 07-lection5/04-input/input.css
> +.input__field {
для этого можно например создать инпут с типом number и пооткрывать его в разных браузерах - без этого свойства а потом с ним

2021-09-09 10:20 UTC, GSemikozov commented on 07-lection5/04-input/input.css
> +  height: 100%;
поскольку лишние зависимости это всегда не очень хорошо. В данном случае мы стилизуем конкретно инпут, и в принципе его высота не должна зависеть от враппера - наоборот, именно враппер может растягиваться в зависимости от высоты инпута

2021-09-10 04:06 UTC, bleschunov commented on 07-lection5/04-input/input.css
> +  height: 100%;
понял

2021-09-10 08:15 UTC, GSemikozov approved these changes

2021-09-10 08:15 UTC, merged