add tabs on main page
js-tasks-ru/htmlcss-20210812_bleshunov5b pull request #25
Opened 2021-09-04 20:56 UTC by bleschunov

2021-09-04 20:56 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-09-05 13:05 UTC, GSemikozov requested changes

2021-09-05 13:05 UTC, GSemikozov commented on components/page/page.css
> +.card_wide {
это модификатор карточки, должен быть определен в файле компонента

2021-09-05 13:05 UTC, GSemikozov commented on components/tabs/tabs.css
> +  flex-wrap: wrap; /* на первое время, чтобы избежать горизонтального скролла*/
а он все равно потребуется - на мобилке

2021-09-05 13:05 UTC, GSemikozov commented on components/tabs/tabs.css
> +  border-bottom: 5px solid var(--grey-8);
лучше определить на уровне item-а, просто по умолчанию сделать прозрачной, а когда active - менять цвет на серый

2021-09-09 09:52 UTC, bleschunov commented on components/tabs/tabs.css
> +  flex-wrap: wrap; /* на первое время, чтобы избежать горизонтального скролла*/
ну это на первое время: когда потребуется скролл, изменю

2021-09-09 09:58 UTC, bleschunov commented on components/page/page.css
> +.card_wide {
сделал

2021-09-09 10:00 UTC, bleschunov commented on components/tabs/tabs.css
> +  border-bottom: 5px solid var(--grey-8);
сделал

2021-09-09 10:09 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-09-09 10:12 UTC, GSemikozov approved these changes

2021-09-09 10:12 UTC, merged