add components: header, main_section, footer
js-tasks-ru/htmlcss-20210812_bleshunov5b pull request #6
Opened 2021-08-19 14:06 UTC by bleschunov

2021-08-19 14:07 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-08-19 14:35 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-08-19 14:53 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-08-19 16:16 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-08-20 08:54 UTC, GSemikozov requested changes

2021-08-20 08:54 UTC, GSemikozov commented on components/footer/footer.css
> +  margin: 71px auto 32px;
вместо марджинов у дочерних элементов которыми отталкиваемся от границ футера сверху и снизу лучше использовать паддинги у самого .footer

2021-08-20 08:54 UTC, GSemikozov commented on components/header/header.css
> +.header__wrapper {
это лишнее, есть стили в preview

2021-08-20 08:54 UTC, GSemikozov commented on components/main_section/main_section.css
> +  height: 500px;
фиксированную высоту лучше убрать (в дальнейшем мы уже знаем как растянуть эту секцию на все допустимое пространство через flex)

2021-08-20 08:54 UTC, GSemikozov commented on components/page/page.css
> +.header__title {
унести в .header (это составная часть header-а)

2021-08-20 16:13 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-08-22 13:07 UTC, bleschunov commented on components/footer/footer.css
> +  margin: 71px auto 32px;
+

2021-08-22 13:08 UTC, bleschunov commented on components/header/header.css
> +.header__wrapper {
учёл

2021-08-22 13:08 UTC, bleschunov commented on components/main_section/main_section.css
> +  height: 500px;
учёл

2021-08-22 13:08 UTC, bleschunov commented on components/page/page.css
> +.header__title {
учёл

2021-08-23 07:36 UTC, GSemikozov approved these changes

2021-08-23 07:36 UTC, merged